"""
main.py - FastAPI Application Entry Point
==========================================
This is the root module that ties together the entire backend:
  1. Creates the FastAPI application instance
  2. Configures CORS (Cross-Origin Resource Sharing) for the React frontend
  3. Registers all API routers under /api/v1/
  4. Seeds the database with sample data on first startup

Running the server:
  Development (auto-reload on file changes):
    uvicorn main:app --reload --port 8000

  Production:
    uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4

Interactive API docs (auto-generated by FastAPI):
  Swagger UI:  http://localhost:8000/docs
  ReDoc:       http://localhost:8000/redoc
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import engine, SessionLocal, Base
import models  # noqa: F401 — imported to register ORM models with Base.metadata
from sample_data import seed_database
from routers import patients, glucose, medications, appointments, stats


# ─────────────────────────────────────────────────────────────────────────────
# Lifespan: startup and shutdown events
# ─────────────────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs setup logic before the server starts accepting requests,
    and teardown after it stops.

    On startup:
      1. Create all database tables (if they don't exist yet).
         Base.metadata.create_all() reads all registered ORM models
         and generates the appropriate CREATE TABLE SQL.
      2. Seed sample data if the database is empty.

    This replaces the deprecated @app.on_event("startup") pattern.
    """
    # ── Create tables ─────────────────────────────────────────────────────────
    Base.metadata.create_all(bind=engine)

    # ── Seed sample data ─────────────────────────────────────────────────────
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()

    yield   # Server is running — handle requests

    # Teardown code (if any) goes here — runs when the server shuts down


# ─────────────────────────────────────────────────────────────────────────────
# FastAPI App Instance
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Diabetes EMR API",
    description="""
## Diabetes-Focused Electronic Medical Records

A mobile-first EMR backend providing structured diabetes clinical data.

### Features
- **Patient management** with diabetes-specific demographics
- **Glucose tracking** with configurable reading types and pagination
- **HbA1c trend data** for longitudinal glycemic control monitoring  
- **Medication management** including insulin regimens
- **Appointment history** with care team notes
- **Dashboard statistics** for population health overview

### Pagination
All list endpoints support `skip` and `limit` query parameters.
Responses include `total` and `has_more` for frontend "Load More" buttons.

### Data
Sample data includes 15 fictional patients representing the full
spectrum of diabetes care (Type 1, Type 2, LADA, Gestational, Prediabetes).
""",
    version="1.0.0",
    lifespan=lifespan,
    # Customize the OpenAPI schema download URLs
    openapi_tags=[
        {"name": "patients",     "description": "Patient demographics and clinical summaries"},
        {"name": "glucose",      "description": "Blood glucose readings and trends"},
        {"name": "medications",  "description": "Prescribed medications"},
        {"name": "appointments", "description": "Clinical visits and scheduling"},
        {"name": "stats",        "description": "Dashboard aggregate statistics"},
    ],
)


# ─────────────────────────────────────────────────────────────────────────────
# CORS Middleware
# ─────────────────────────────────────────────────────────────────────────────
# CORS must be configured to allow the Next.js frontend (running on port 3000)
# to call the FastAPI backend (port 8000). Without this, the browser blocks
# cross-origin requests.
#
# In production:
#   - Replace "*" with your actual frontend domain(s)
#   - Example: allow_origins=["https://your-emr.example.com"]
#   - Never use allow_origins=["*"] in production with allow_credentials=True

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",    # Next.js dev server
        "http://127.0.0.1:3000",   # Alternative localhost notation
        "http://142.93.62.131",    # Production droplet
    ],
    allow_credentials=True,
    allow_methods=["*"],            # GET, POST, PUT, PATCH, DELETE, OPTIONS
    allow_headers=["*"],            # Content-Type, Authorization, etc.
)


# ─────────────────────────────────────────────────────────────────────────────
# API Routers
# ─────────────────────────────────────────────────────────────────────────────
# Each router is a separate module that handles a domain of endpoints.
# The prefix /api/v1 is added to all routes for versioning.
# If a breaking API change is needed in the future, add /api/v2 routers
# while keeping /api/v1 working for existing clients.

app.include_router(patients.router,     prefix="/api/v1", tags=["patients"])
app.include_router(glucose.router,      prefix="/api/v1", tags=["glucose"])
app.include_router(medications.router,  prefix="/api/v1", tags=["medications"])
app.include_router(appointments.router, prefix="/api/v1", tags=["appointments"])
app.include_router(stats.router,        prefix="/api/v1", tags=["stats"])


# ─────────────────────────────────────────────────────────────────────────────
# Root Health Check
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/", tags=["health"])
def health_check():
    """
    Simple health-check endpoint.
    Used by load balancers, container orchestrators (Kubernetes liveness probes),
    and monitoring tools to verify the service is running.
    """
    return {
        "status": "healthy",
        "service": "Diabetes EMR API",
        "version": "1.0.0",
        "docs": "/docs",
    }
